---
# tasks file for ansible-role-argus-clients

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ argus-clients_log_dir }}"
    mode: 0755
    owner: "{{ argus-clients_user }}"
    group: "{{ argus-clients_group }}"
    state: directory
  notify: Restart argus-clients

- name: Create db directory
  file:
    path: "{{ argus-clients_db_dir }}"
    mode: 0755
    owner: "{{ argus-clients_user }}"
    group: "{{ argus-clients_group }}"
    state: directory
  notify: Restart argus-clients

- name: Create argus-clients.conf
  template:
    src: argus-clients.conf.j2
    dest: "{{ argus-clients_conf_file }}"
    validate: echo %s
  notify: Restart argus-clients

- name: Start argus-clients
  service:
    name: "{{ argus-clients_service }}"
    enabled: true
    state: started
