---
# tasks file for ansible-role-argus-clients

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create ra.conf
  template:
    src: ra.conf.j2
    dest: "{{ argus_clients_config_dir }}/ra.conf"
